version: "3.5"
services:
  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    user: root
    volumes:
      - wp:/var/www/html/wordpress
    networks:
     - supa-dupa-network
    depends_on:
      - wordpress
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    build: ./wp
    volumes:
      - wp:/var/www/html/wordpress
    restart: always
    networks:
      - supa-dupa-network
    depends_on:
      - mariadb
    env_file:
          - ../.env


  mariadb:
    container_name: mariadb
    build: ./db
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - supa-dupa-network
    env_file:
      - ../.env


networks:
  supa-dupa-network:
    name: supa-dupa-network


volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  home/${USER}/data/db
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device:  /home/${USER}/data/wp

#TODO mysql bind 0.0.0.0